### ISSUE TITLE
Criar primeira versão do modulo de ECS

### ISSUE THREAD

**Issue by afonsoaugusto** [mentoriaiac/iac-modulo-aws-ecs#1]
O objetivo do modulo é criar um cluster ECS para rodar uma imagem docker.
Este modulo será utilizado por dois projetos que a [mentoriaIaC](https://mentoriaiac.com/) apoia:
- [DadosAbertos da Feira](https://github.com/DadosAbertosDeFeira)
- MTST

### Dependencias

Inicialmente podemos considerar que o ambiente do ECS já vai ter uma VPC disponível.
O modulo pode ficar contido apenas no cluster e nas estrutura básica para ele.

### DoD

Primeira versão do modulo que crie um cluster ECS com os objetos:
- Cluster ECS
- Task Definition
- Service

Um plus seria:
- Security group
- Task Role
- Task role execution
- Auto scaling
- Load Balancer (Application, Network)

**Comment by EzzioMoreira** [comment]
Primeira versão foi entregue feita merge da branch.
